name: Send email testing 
on: [push, pull_request]
jobs:
  notification:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Shorten sha 
        run: echo "SHORT_SHA=`echo ${github.sha} | cut -c1-8`" >> $GITHUB_ENV


      - name: Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{secrets.NETIVISM_EMAIL_HOST}}
          server_port: ${{secrets.NETIVISM_EMAIL_PORT}}
          username: ${{secrets.NETIVISM_EMAIL_LOGIN}}
          password: ${{secrets.NETIVISM_EMAIL_PASSWD}}
          to: ${{secrets.NETIVISM_NOTIFICATION_TARGET}}
          from: Github Notification
          secure: false
          ignore_cert: true
          convert_markdown: true
          subject: "[${{ github.repository }}] Run ${{ job.status }}: CI Testing - ${{github.ref_name}} (${{SHORT_SHA}})"
          body: |
            Executed by: ${{github.actor}}
            Job name: ${{github.job}}
            Repository: ${{github.repository}}
            Status: ${{job.status}}
            Link: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}

