name: Send email testing 
on: [push, pull_request]
jobs:
  notification:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Shorten sha 
        id: vars
        shell: bash
        run: echo "::set-output name=sha_short::${GITHUB_SHA::7}"

      - name: Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{secrets.NETIVISM_EMAIL_HOST}}
          server_port: ${{secrets.NETIVISM_EMAIL_PORT}}
          username: ${{secrets.NETIVISM_EMAIL_LOGIN}}
          password: ${{secrets.NETIVISM_EMAIL_PASSWD}}
          to: ${{secrets.NETIVISM_NOTIFICATION_TARGET}}
          from: Github Workflow
          secure: false
          ignore_cert: true
          convert_markdown: true
          subject: "[${{github.repository}}] Run ${{job.status}}: ${{github.workflow}} - ${{github.ref_name}} (${{steps.vars.outputs.sha_short}})"
          body: |
            Executed by: ${{github.actor}}
            Job name: ${{github.job}}
            Repository: ${{github.repository}}
            Status: ${{job.status}}
            SHA: ${{github.sha}}
            Message: ${{ github.event.head_commit.message }}
            Link: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}

